# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96bd2a9749bba7393b638ba757c09998e852a9f8d55b2beaf5db7aae8f2b37e1b56271a00e6d210a39b2b43c4cf285767604892ea4eee232b39bc40a0d260b64

test:
  secret_key_base: eb1f2a42ca090c044504d847cbf6d944164b94fbc4b0391e9baf8f7888123ad18490028d84c3646912c40c96932fffcfbd13f16c916ea0c1702a80e5fb545294

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
